<div class="wrapper-md bg-white b-b box-shadow">
    <h1 class="m-n font-thin h3">
        <span class="fa fa-calendar"></span>
        <?= $this->translate('title.event', 'admin') ?>
    </h1>
</div>

<div class="wrapper-md">
    <div class="row">
        <div class="col-md-6">
            <form class="form-horizontal" role="form" action="<?= $this->url(null, [], [], true) ?>" method="post">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <?php if ($this->event): ?>
                            <span class="panel-title">
                                <?= $this->event->getTitle() ?>
                            </span>
                        <?php else: ?>
                            <span class="panel-title">
                            New Event
                        </span>
                        <?php endif ?>
                    </div>
                    <div class="panel-body">
                        <?= $this->form($this->form) ?>
                    </div>
                    <div class="panel-footer">
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-md-10">
                                <button type="submit" class="btn btn-primary">
                                    <span class="fa fa-save"></span>
                                    <?= $this->translate('button.save', 'admin') ?>
                                </button>

                                <?php if ($this->params()->fromRoute('isEditMode') == true): ?>
                                    <delete
                                        url="<?= $this->url('admin/event/delete') ?>"
                                        title="<?= $this->translate("event.modal.delete.title", "admin") ?>"
                                        content="<?= $this->translate("event.modal.delete.content", "admin") ?>"
                                        request-id="<?= $this->event->getId() ?>"
                                        >
                                    </delete>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

