<div class="wrapper-md bg-white b-b box-shadow">
    <h1 class="m-n font-thin h3">
        <span class="fa fa-calendar"></span>
        <?= $this->translate('title.calendar', 'admin') ?>
    </h1>
</div>

<div class="wrapper-md"
     ng-controller="CalendarController"
     data-request-url="<?= /*$this->url('admin/calendar/list')*/
     '' ?>"
     data-save-url="<?= /*$this->url('admin/calendar/save')*/
     '' ?>"
     data-add-url="<?= /*$this->url('admin/calendar/add-event')*/
     '' ?>"
     data-active-locale="<?= $this->localization()->getDefaultLocale() ?>"
    >
    <div class="panel panel-default">
        <div class="hbox hbox-auto-xs hbox-auto-sm">
            <div class="col wrapper-md">

                <!--<ul class="nav nav-tabs" ng-class="{'nav-stacked': vertical, 'nav-justified': justified}" ng-transclude="">-->
                <!--    <li ng-class="{active: active, disabled: disabled}" select="renderCalender('myCalendar1');" class="ng-isolate-scope active">-->
                <!--        <a ng-click="select()" tab-heading-transclude="" class="ng-binding"><tab-heading class="ng-scope">-->
                <!--                <i class="glyphicon glyphicon-bell"></i> Calendar One-->
                <!--            </tab-heading></a>-->
                <!--    </li>-->
                <!--    <li ng-class="{active: active, disabled: disabled}" select="renderCalender('myCalendar2');" class="ng-isolate-scope">-->
                <!--        <a ng-click="select()" tab-heading-transclude="" class="ng-binding"><tab-heading class="ng-scope">-->
                <!--                <i class="glyphicon glyphicon-bell"></i> Calendar Two-->
                <!--            </tab-heading></a>-->
                <!--    </li>-->
                <!--    <li ng-class="{active: active, disabled: disabled}" select="renderCalender('myCalendar3');" class="ng-isolate-scope">-->
                <!--        <a ng-click="select()" tab-heading-transclude="" class="ng-binding"><tab-heading class="ng-scope">-->
                <!--                <i class="glyphicon glyphicon-bell"></i> Calendar Three-->
                <!--            </tab-heading></a>-->
                <!--    </li>-->
                <!--</ul>-->

                <div class="clearfix m-b">
                    <button type="button" tooltip="Double click on calendar day to create event"
                            class="btn btn-sm btn-primary btn-addon" ng-click="addEvent()">
                        <i class="fa fa-plus"></i> <?= $this->translate('button.event-add', 'admin') ?>
                    </button>
                    <div class="pull-right">
                        <button type="button" class="btn btn-sm btn-default" ng-click="today()"><?= $this->translate('button.today', 'admin') ?></button>
                        <div class="btn-group m-l-xs">
                            <button class="btn btn-sm btn-default" ng-click="changeView('agendaDay')"><?= $this->translate('button.day', 'admin') ?></button>
                            <button class="btn btn-sm btn-default" ng-click="changeView('agendaWeek')"><?= $this->translate('button.week', 'admin') ?></button>
                            <button class="btn btn-sm btn-default" ng-click="changeView('month')"><?= $this->translate('button.month', 'admin') ?></button>
                        </div>
                        <button type="button" class="btn btn-sm btn-default m-l-xs" ui-toggle-class="show"
                                target="#calendarList">
                            <i class="fa fa-bars"></i> <?= $this->translate('button.list', 'admin') ?>
                        </button>
                    </div>
                </div>
                <div class="pos-rlt">
                    <div class="fc-overlay">
                        <div class="panel bg-white b-a pos-rlt">
                            <span class="arrow"></span>

                            <div class="h4 font-thin m-b-sm">{{event.title}}</div>
                            <div class="line b-b b-light"></div>

                            <div>
                                <i class="icon-calendar text-muted m-r-xs"></i> {{event.start | date:'mediumDate'}}
                                <span class="ng-hide" ng-hide="event.allDay"> {{event.start | date:'shortTime'}}</span>
                            </div>
                            <div class="ng-hide" ng-show="event.end">
                                <i class="icon-clock text-muted m-r-xs"></i> {{event.end | exclusiveEndDate:'mediumDate':event.allDay}}
                                <span class="ng-hide" ng-hide="event.allDay"> {{event.end | date:'shortTime'}}</span>
                            </div>

                            <div class="ng-hide" ng-show='event.location'>
                                <i class="icon-pointer text-muted m-r-xs"></i> {{event.location}}
                            </div>
                            <div class="m-t-sm">{{event.info}}</div>
                            <div class="m-t-sm">{{event.url}}</div>
                        </div>
                    </div>
                    <div class="calendar"
                         calendar="calendar1"
                         ng-model="eventSources"
                         config="uiConfig.calendar"
                         ui-calendar="uiConfig.calendar"
                         calendar-watch-event="extraEventSignature(event)"
                        ></div>
                </div>
            </div>
            <div class="col w-md w-auto-xs bg-light dk bg-auto b-l hide" id="calendarList">
                <div class="wrapper">
                    <div ng-repeat="event in events | orderBy:'startTimestamp'"
                         class="bg-white-only r r-2x m-b-xs wrapper-sm {{event.className[0]}}">

                        <input ng-model="event.title" class="form-control m-t-n-xs no-border no-padder no-bg">

                        <a class="pull-right text-xs text-muted" ng-click="removeEvent($index)">
                            <i class="fa fa-trash-o"></i>
                        </a>

                        <div class="text-xs text-muted">
                            {{event.start | date:'mediumDate':'+0200'}}<span class="ng-hide" ng-hide="event.allDay"> {{event.start | date:'shortTime'}}</span>
                            <span ng-show="event.end"> - {{event.end | exclusiveEndDate:'mediumDate':event.allDay}}
                                <span class="ng-hide" ng-hide="event.allDay"> {{event.end | date:'shortTime'}}</span>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
