<div class="wrapper-md bg-white b-b box-shadow">
    <h1 class="m-n font-thin h3">
        <span class="fa fa-calendar"></span>
        <?= $this->translate('title.calendar.list', 'admin') ?>
    </h1>
</div>

<div class="wrapper-md">
    <div class="panel panel-default">

        <div class="panel-heading">
            <span class="panel-title">
                Calendars
                <a class="btn btn-xs btn-default" href="<?= $this->url('admin/calendar') ?>">
                    <i class="fa fa-bars"></i> Show All Events
                </a>
            </span>
        </div>

        <div class="panel-body">
            <table class="table table-striped table-hover">
                <tbody>
                    <?php foreach ($calendars as $calendar): ?>
                        <?php $settings = json_decode($calendar->settings)?>
                        <tr>
                            <td style="vertical-align: middle">
                                <?php if($this->permission('admin42')->isGranted('route/admin/calendar/calendar')): ?>
                                <a href="<?= $this->url('admin/calendar/calendar', ['id' => $calendar->id]) ?>">
                                    <?php if(!is_null($settings->color)): ?>
                                        <span class="fa fa-square" style="color: <?= $settings->color ?>;"></span> <?= $calendar->title ?>
                                    <?php else: ?>
                                        <span class="fa fa-square text-primary"></span> <?= $calendar->title ?>
                                    <?php endif ?>
                                </a>
                                <?php endif; ?>
                            </td>
                            <td class="text-right">
                                <?php if($this->permission('admin42')->isGranted('route/admin/event/add')): ?>
                                <a href="<?= $this->url('admin/event/add') ?>?calendarId=<?= $calendar->id ?>" class="btn btn-xs btn-default">
                                    <span class="fa fa-plus"></span> Add Event
                                </a>
                                <?php endif; ?>
                                <?php if($this->permission('admin42')->isGranted('route/admin/calendar/edit')): ?>
                                <a href="<?= $this->url('admin/calendar/edit', ['id' => $calendar->id]) ?>" class="btn btn-xs btn-info">
                                    <span class="fa fa-pencil"></span>
                                </a>
                                <?php endif; ?>
                                <?php if($this->permission('admin42')->isGranted('route/admin/calendar/delete')): ?>
                                <delete
                                    url="<?= $this->url('admin/calendar/delete') ?>"
                                    title="<?= $this->translate("calendar.modal.delete.title", "admin") ?>"
                                    size="xs"
                                    content="<?= $this->translate("calendar.modal.delete.content", "admin") ?>"
                                    request-id="<?= $calendar->id ?>"
                                    >
                                </delete>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>

        <div class="panel-footer">
            <?php if($this->permission('admin42')->isGranted('route/admin/calendar/add')): ?>
            <a href="<?= $this->url('admin/calendar/add') ?>" class="btn btn-default">
                <i class="fa fa-plus"></i> <?= $this->translate('button.calendar-add', 'admin') ?>
            </a>
            <?php endif; ?>
        </div>

    </div>
</div>
