<div class="wrapper-md bg-white b-b box-shadow">
    <h1 class="m-n font-thin h3">
        <span class="fa fa-calendar"></span>
        <?= $this->translate('title.calendar.list', 'admin') ?>
    </h1>
</div>

<div class="wrapper-md">
    <div class="panel panel-default">
        <div class="panel-body">
            <table class="table table-striped table-hover">
                <tbody>
                    <?php foreach ($calendars as $calendar): ?>
                        <tr>
                            <td>
                                <a href="<?= $this->url('admin/calendar/calendar', ['id' => $calendar->id]) ?>">
                                    <?= $calendar->title ?>
                                </a>
                            </td>
                            <td class="text-right">
                                <a href="<?= $this->url('admin/event/add') ?>?calendarId=<?= $calendar->id ?>" class="btn btn-sm btn-default">
                                    <span class="fa fa-plus"></span> Add Event
                                </a>
                                <a href="<?= $this->url('admin/calendar/edit', ['id' => $calendar->id]) ?>" class="btn btn-sm btn-info">
                                    <span class="fa fa-pencil"></span>
                                </a>
                                <delete
                                    url="<?= $this->url('admin/calendar/delete') ?>"
                                    title="<?= $this->translate("calendar.modal.delete.title", "admin") ?>"
                                    size="xs"
                                    content="<?= $this->translate("calendar.modal.delete.content", "admin") ?>"
                                    request-id="<?= $calendar->id ?>"
                                    >
                                </delete>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
        <div class="panel-footer">
            <a href="<?= $this->url('admin/calendar/add') ?>" class="btn btn-default">
                <i class="fa fa-plus"></i> <?= $this->translate('button.calendar-add', 'admin') ?>
            </a>
        </div>
    </div>
</div>
